name = "learning-log-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "learning-log"
database_id = "027f5e7d-b89b-4847-8e62-d2cc317fbe0e"
